import "bootstrap/dist/css/bootstrap.min.css";
import mypic from "../public/images/8401.jpg";
import Head from "next/head";
import Image from "next/image";
import Navhome from "../components/common/Navbar";

import Formhome from "../components/common/Form";

export default function Home({ data }) {
  return (
    <div className="bg-blue-50 h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navhome />
      <div className="mt-big"></div>

      <div className="flex justify">
        <div className="grow-1 flex">
          <Formhome />
        </div>
        <div className="grow-1 img-container">
          <Image
            className="image-bg"
            src={mypic}
            alt="freepik illustraition"
            height={380}
            width={600}
          />
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {},
    revalidate: 10,
  };
}
